---
apiVersion: v1
kind: Namespace
metadata:
  name: vm00101
  labels:
    name: vm00101
---
apiVersion: v1
kind: Secret
metadata:
  name: ibi-pull-secret
  namespace: vm00101
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "IHsiYXV0aHMiOiB7ImUzOC1oMDEtMDAwLXI2NTAucmR1Mi5zY2FsZWxhYi5yZWRoYXQuY29tOjUwMDAiOiB7ImF1dGgiOiAiY21WbmFYTjBjbms2Y21WbmFYTjBjbms9In19fQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: vm00101-bmc-secret
  namespace: vm00101
type: Opaque
data:
  password: cGFzc3dvcmQ=
  username: cmVkaGF0
---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: vm00101
  namespace: vm00101
spec:
  additionalNTPSources:
  - fc00:1005::24
  baseDomain: rdu2.scalelab.redhat.com
  clusterImageSetNameRef: openshift-4.20.0-rc.3
  extraLabels:
    ManagedCluster:
      common: 'true'
      group-du-sno: ''
      name: vm00101
      observability: enabled
      sites: vm00101
  clusterName: vm00101
  clusterNetwork:
  - cidr: fd01::/48
    hostPrefix: 64
  clusterType: SNO
  holdInstallation: false
  machineNetwork:
  - cidr: fc00:1005::/64
  networkType: OVNKubernetes
  nodes:
  - automatedCleaningMode: disabled
    bmcAddress: redfish-virtualmedia+http://[fc00:1005::24]:9000/redfish/v1/Systems/d9c1f433-e915-5f98-baa8-5bfce73a7905
    bmcCredentialsName:
      name: vm00101-bmc-secret
    bootMACAddress: 52:54:00:00:00:65
    bootMode: UEFI
    hostName: vm00101
    ironicInspect: disabled
    nodeNetwork:
      interfaces:
      - name: enp1s0
        macAddress: 52:54:00:00:00:65
      config:
        interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          identifier: mac-address
          mac-address: 52:54:00:00:00:65
          ipv4:
            enabled: false
          ipv6:
            enabled: true
            autoconf: false
            dhcp: false
            address:
            - ip: fc00:1005::44c
              prefix-length: 64
        dns-resolver:
          config:
            server:
            - fc00:1005::24
        routes:
          config:
          - destination: ::/0
            next-hop-address: fc00:1005::1
            next-hop-interface: enp1s0
    templateRefs:
      - name: ibi-node-templates-v1
        namespace: open-cluster-management
  pullSecretRef:
    name: ibi-pull-secret
  serviceNetwork:
  - cidr: fd02::/112
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6351YHGIvE6DZcAt0RXqodzKbglUeCNqxRyd7OOfcN+p88RaKZahg9/dL81IbdlGPbhPPG9ga7BdkLN8VbyYNCjE7kBIKM47JS1pbjeoJhI8bBrFjjp6LIJW/tWh1Pyl7Mk3DbPiZOkJ9HXvOgE/HRh44jJPtMLnzrZU5VNgNRgaEBWOG+j06pxdK9giMji1mFkJXSr43YUZYYgM3egNfNzxeTG0SshbZarRDEKeAlnDJkZ70rbP2krL2MgZJDv8vIK1PcMMFhjsJ/4Pp7F0Tl2Rm/qlZhTn4ptWagZmM0Z3N2WkNdX6Z9i2lZ5K+5jNHEFfjw/CPOFqpaFMMckpfFMsAJchbqnh+F5NvKJSFNB6L77iRCp5hbhGBbZncwc3UDO3FZ9ZuYZ8Ws+2ZyS5uVxd5ZUsvZFO+mWwySytFbsc0nUUcgkXlBiGKF/eFm9SQTURkyNzJkJfPm7awRwYoidaf8MTSp/kUCCyloAjpFIOJAa0SoVerhLp8uhQzfeU= root@e38-h01-000-r650.rdu2.scalelab.redhat.com
  templateRefs:
    - name: ibi-cluster-templates-v1
      namespace: open-cluster-management
 
