apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
    name: disconnected-internal-idms
    annotations:
        ran.openshift.io/ztp-deploy-wave: "1"
spec:
#    imageDigestMirrors:
#    - $mirrors
