---
apiVersion: v1
kind: Namespace
metadata:
  name: vm008
  labels:
    name: vm008
---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: vm008-clusterinstance
  namespace: vm008
spec:
  extraLabels:
    ManagedCluster:
      logicalGroup: "25b"
      group-du-sno: ""
      common: "true"
      siteName: "eric-vdu-spr"
      eric-vdu: ""
      infra: "faregde"
      server: "VM"
      pao: "true"
      sriov: "true"
      sno: "true"
      mcp: "master"
      vendor: "OpenShift"
      cluster.open-cluster-management.io/clusterset: "rbac-mcs-sno"
      acmName: "rchltx-acm-2.faredge.vzwops.com"
      dataCenter: "richardsonNEC"
      hostName: "hv-3-sno-5"
      logRegion: "midwest"
      cnfIdentifier: "rchltxef-93180000vzwcgnb-y-ec-x-99988880305"
      gnbDuID: "99988880305"
      vduNamespace: "hv-3-sno-5-ec-gnb-001"
      vduCrdNamespace: "hv-3-sno-5-ec-gnb-crd"
  baseDomain: qe.red-chesterfield.com
  clusterImageSetNameRef: img4.19.15-x86-64-appsub
  clusterName: vm008
  clusterType: SNO
  cpuArchitecture: x86_64
  cpuPartitioningMode: None
  holdInstallation: false
  networkType: OVNKubernetes
  nodes:
  - automatedCleaningMode: metadata
    bmcAddress: redfish-virtualmedia://192.168.123.1:8000/redfish/v1/Systems/84b8f89a-fbff-412c-963f-d9104d1d9c66
    bmcCredentialsName:
      name: vm008-bmc-secret
    bootMACAddress: 52:54:00:40:04:a3
    bootMode: UEFI
    hostName: vm008
    ironicInspect: ""
    role: master
    templateRefs:
    - name: ibi-node-templates-v1
      namespace: open-cluster-management
  pullSecretRef:
    name: assisted-deployment-pull-secret
  templateRefs:
  - name: ibi-cluster-templates-v1
    namespace: open-cluster-management
