apiVersion: v1
kind: ConfigMap
metadata:
  name: log-secret
  namespace: ztp-group-du-sno
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  caBundleCrt: "<<VCMP Kafka CA Certificate>>"
  tlsCrt: "<<VCMP Kafka Client Certificate>>"
  tlsKey: "<<VCMP Kafka Client Private Key>>"
